name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
env:
  IMAGE_NAME: docker-gui-server
  IMAGE_TAGNAME: latest

jobs:
  package:
    name: Packaging backend
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{secrets.GB_TOKEN}}
      GH_USERNAME: assifar-karim
      GH_DOCKER_REGISTRY: ghcr.io
    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        run: |
          docker login $GH_DOCKER_REGISTRY -u $GH_USERNAME -p $GH_TOKEN
      - name: Build docker image
        run: docker build . --file Dockerfile-pckg -t $GH_DOCKER_REGISTRY/$GH_USERNAME/$IMAGE_NAME:$IMAGE_TAGNAME
      - name: Docker push
        run: docker push $GH_DOCKER_REGISTRY/$GH_USERNAME/$IMAGE_NAME:$IMAGE_TAGNAME
